"""Reports_table

Revision ID: 269522bccb2f
Revises: 3665d5c63dd2
Create Date: 2022-03-07 15:08:45.701211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269522bccb2f'
down_revision = '3665d5c63dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('issue', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bookings', 'expiry',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'expiry',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_table('reports')
    # ### end Alembic commands ###
