"""UPDATING-TABLE

Revision ID: 3665d5c63dd2
Revises: a9c1f5f7123e
Create Date: 2022-02-24 15:11:27.506764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3665d5c63dd2'
down_revision = 'a9c1f5f7123e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('bookings', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('expiry', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'expiry')
    op.drop_column('bookings', 'active')
    # ### end Alembic commands ###
