"""empty message

Revision ID: 3de26e58327b
Revises: f164155d3bb8
Create Date: 2022-04-28 15:01:44.068116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de26e58327b'
down_revision = 'f164155d3bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('discount', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discount')
    op.drop_column('users', 'staff')
    # ### end Alembic commands ###
