"""empty message

Revision ID: 7c7005619335
Revises: a1f4219d5c63
Create Date: 2022-04-20 16:44:58.182865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7005619335'
down_revision = 'a1f4219d5c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discount', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discount')
    # ### end Alembic commands ###
