"""added_cards_table

Revision ID: e5f96d4052f0
Revises: 3665d5c63dd2
Create Date: 2022-03-15 15:40:49.199488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f96d4052f0'
down_revision = '3665d5c63dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cardnum', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('bookings', 'expiry',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('bookings', 'expiry',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    op.drop_table('cards')
    # ### end Alembic commands ###
